public class T {
   public static String AA;
   public static String AB;
   public static String del;
   public static String AD;
   public static String close;
   public static String AF;
   public static String AG;
   public static String AH;
   public static String AI;
   public static String AJ;
   public static String AK;
   public static String gohome;
   public static String revice;
   public static String AN;
   public static String hoiRevice;
   public static String hoiGoHome;
   public static String AQ;
   public static String AR;
   public static String AS;
   public static String AT;
   public static String AU;
   public static String tabInven;
   public static String AW;
   public static String AX;
   public static String AY;
   public static String AZ;
   public static String BA;
   public static String BB;
   public static String BC;
   public static String BD;
   public static String BE;
   public static String tabInfo;
   public static String BG;
   public static String BH;
   public static String BI;
   public static String BJ;
   public static String tabSkill;
   public static String BL;
   public static String BM;
   public static String BN;
   public static String BO;
   public static String BP;
   public static String BQ;
   public static String remove;
   public static String HoiSellENG;
   public static String HoiRemoveENG;
   public static String BU;
   public static String BV;
   public static String BW;
   public static String tabEquip;
   public static String BY;
   public static String BZ;
   public static String CA;
   public static String CB;
   public static String CC;
   public static String CD;
   public static String CE;
   public static String CF;
   public static String CG;
   public static String CH;
   public static String CI;
   public static String CJ;
   public static String CK;
   public static String CL;
   public static String CM;
   public static String CN;
   public static String CO;
   public static String CP;
   public static String CQ;
   public static String CR;
   public static String CS;
   public static String CT;
   public static String CU;
   public static String CV;
   public static String CW;
   public static String CX;
   public static String checkRegister1;
   public static String CZ;
   public static String DA;
   public static String setting;
   public static String DC;
   public static String DD;
   public static String DE;
   public static String DF;
   public static String DG;
   public static String DH;
   public static String typeSkill;
   public static String autoMPHP;
   public static String autoFire;
   public static String on;
   public static String off;
   public static String DN;
   public static String DO;
   public static String DP;
   public static String DQ;
   public static String DR;
   public static String DS;
   public static String DT;
   public static String DU;
   public static String DV;
   public static String DW;
   public static String DX;
   public static String DY;
   public static String DZ;
   public static String EA;
   public static String cmdget;
   public static String EC;
   public static String ED;
   public static String manaLost;
   public static String fullInven;
   public static String autoGetItem;
   public static String EH;
   public static String EI;
   public static String EJ;
   public static String EK;
   public static String EL;
   public static String EM;
   public static String EN;
   public static String tacdung;
   public static String EP;
   public static String EQ;
   public static String ER;
   public static String ES;
   public static String ET;
   public static String EU;
   public static String bery;
   public static String EW;
   public static String EX;
   public static String EY;
   public static String EZ;
   public static String nhanduoc;
   public static String FB;
   public static String FC;
   public static String FD;
   public static String FE;
   public static String FF;
   public static String FG;
   public static String FH;
   public static String FI;
   public static String FJ;
   public static String FK;
   public static String FL;
   public static String FM;
   public static String FN;
   public static String FO;
   public static String FP;
   public static String FQ;
   public static String FR;
   public static String FS;
   public static String FT;
   public static String FU;
   public static String FV;
   public static String FW;
   public static String FX;
   public static String FY;
   public static String FZ;
   public static String GA;
   public static String GB;
   public static String GC;
   public static String GD;
   public static String GE;
   public static String tabAttribute;
   public static String GG;
   public static String GH;
   public static String GI;
   public static String GJ;
   public static String GK;
   public static String GL;
   public static String GM;
   public static String GN;
   public static String GO;
   public static String GP;
   public static String split;
   public static String joinItem;
   public static String join;
   public static String nhapsoluongmuonghep;
   public static String chuyenkeypad;
   public static String chuyentouch;
   public static String tatdosat;
   public static String batdosat;
   public static String trade;
   public static String strlock;
   public static String tradeMoney;
   public static String strconfirm;
   public static String nhapsotien;
   public static String eventTrade;
   public static String yeucaugiaodich;
   public static String nhapsoluongmuongiaodich;
   public static String playerShiper;
   public static String ship;
   public static String changeship;
   public static String HJ;
   public static String HK;
   public static String HL;
   public static String HM;
   public static String allMaterial;
   public static String HO;
   public static String HP;
   public static String HQ;
   public static String HR;
   public static String soluong;
   public static String HT;
   public static String HU;
   public static String HV;
   public static String HW;
   public static String HX;
   public static String skillActive;
   public static String skillActiveSea;
   public static String skillBuff;
   public static String skillPassive;
   public static String skillJob;
   public static String ID;
   public static String IE;
   public static String IF;
   public static String IG;
   public static String IH;
   public static String II;
   public static String IJ;
   public static String IK;
   public static String newGame;
   public static String changeAcc;
   public static String IN;
   public static String IO;
   public static String IP;
   public static String IQ;
   public static String IR;
   public static String IS;
   public static String IT;
   public static String IU;
   public static String IV;
   public static String IW;
   public static String daTrangBi;
   public static String IY;
   public static String IZ;
   public static String morong;
   public static String laytatca;
   public static String KC;
   public static String KD;
   public static String KE;
   public static String muonlayrabaonhieu;
   public static String nhapsoluong;
   public static String KH;
   public static String KI;
   public static String KJ;
   public static String KK;
   public static String KL;
   public static String KM;
   public static String KN;
   public static String KO;
   public static String KP;
   public static String KQ;
   public static String KR;
   public static String KS;
   public static String KT;
   public static String KU;
   public static String KV;
   public static String KW;
   public static String KX;
   public static String KY;
   public static String KZ;
   public static String LA;
   public static String LB;
   public static String LC;
   public static String LD;
   public static String LE;
   public static String LF;
   public static String LG;
   public static String LH;
   public static String tabTestAdmin;
   public static String LJ;
   public static String LK;
   public static String LL;
   public static String LM;
   public static String LN;
   public static String LO;
   public static String LP;
   public static String LQ;
   public static String LR;
   public static String LS;
   public static String LT;
   public static String loadGame;
   public static String LV;
   public static String LW;
   public static String LX;
   public static String LY;
   public static String LZ;
   public static String MA;
   public static String MB;
   public static String MC;
   public static String MD;
   public static String ME;
   public static String MF;
   public static String MG;
   public static String MH;
   public static String helpAutoRevice;
   public static String MJ;
   public static String MK;
   public static String ML;
   public static String MM;
   public static String Clan;
   public static String anhem;
   public static String phuttruoc;
   public static String gio;
   public static String thuyentruong;
   public static String thuyenpho;
   public static String hoatieu;
   public static String thanhvien;
   public static String tangqua;
   public static String nhiemvu;
   public static String capdo;
   public static String kickClan;
   public static String strDonate;
   public static String phongchuc;
   public static String clanLeave;
   public static String banmuon;
   public static String ND;
   public static String chiso;
   public static String NF;
   public static String NG;
   public static String NH;
   public static String NI;
   public static String NJ;
   public static String NK;
   public static String NL;
   public static String NM;
   public static String NN;
   public static String NO;
   public static String NP;
   public static String NQ;
   public static String NR;
   public static String NS;
   public static String NT;
   public static String NU;
   public static String NV;
   public static String NW;
   public static String NX;
   public static String NY;
   public static String NZ;
   public static String PA;
   public static String PB;
   public static String PC;
   public static String PD;
   public static String PE;
   public static String PF;
   public static String PG;
   public static String PH;
   public static String PI;
   public static String PJ;
   public static String PK;
   public static String PL;
   public static String PM;
   public static String showHat;
   public static String PO;
   public static String PP;
   public static String PQ;
   public static String PR;
   public static String PS;
   public static String PT;
   public static String PU;
   public static String PV;
   public static String PW;
   public static String PX;
   public static String PY;
   public static String PZ;
   public static String QA;
   public static String QB;
   public static String QC;
   public static String max;
   public static String QE;
   public static String QF;
   public static String lvDevil;
   public static String QH;
   public static String QI;
   public static String QJ;
   public static String QK;
   public static String QL;
   public static String QM;
   public static String QN;
   public static String QO;
   public static String QP;
   public static String QQ;
   public static String open;
   public static String tabQuest;
   public static String QT;
   public static String QU;
   public static String QV;
   public static String QW;
   public static String server;
   public static String QY;
   public static String QZ;
   public static String RA;
   public static String RB;
   public static String RC;
   public static String RD;
   public static String RE;
   public static String RF;
   public static String RG;
   public static String RH;
   public static String RI;
   public static String RJ;
   public static String RK;
   public static String RL;
   public static String RM;
   public static String RN;
   public static String RO;
   public static String RP;
   public static String RQ;
   public static String RR;
   public static String RS;
   public static String RT;
   public static String RU;
   public static String RV;
   public static String RW;
   public static String RX;
   public static String RY;
   public static String RZ;
   public static String SA;
   public static String SB;
   public static String SC;
   public static String SD;
   public static String SE;
   public static String SF;
   public static String SG;
   public static String SH;
   public static String SI;
   public static String SJ;
   public static String SK;
   public static String SL;
   public static String SM;
   public static String showSkillBuff;
   public static String SO;
   public static String SP;
   public static String SQ;
   public static String SR;
   public static String SS;
   public static String ST;
   public static String SU;
   public static String SV;
   public static String SW;
   public static String SX;
   public static String SY;
   public static String SZ;
   public static String thongtinfullset;
   public static String thongtinchiso;
   public static String TC;
   public static String TD;
   public static String TE;
   public static String TF;
   public static String TG;
   public static String TH;
   public static String TI;
   public static String TJ;
   public static String TK;
   public static String TL;
   public static String TM;
   public static String TN;
   public static String TO;
   public static String TP;
   public static String tabSieuBoss;
   public static String TR;
   public static String TS;
   public static String TT;
   public static String chuan;
   public static String TV;
   public static String TW;
   public static String TX;
   public static String TY;
   public static String TZ;
   public static String UA;
   public static String UB;
   public static String UC;
   public static String UD;
   public static String UE;
   public static String UF;
   public static String UG;
   public static String UH;
   public static String UI;
   public static String UJ;
   public static String UK;
   public static String UL;
   public static String UM;
   public static String UN;
   public static String UO;
   public static String UP;
   public static String UQ;
   public static String showSkillPlayer;
   public static String showNhanVat;
   public static String UT;
   public static String UU;
   public static String UV;
   public static String UW;
   public static String UX;
   public static String UY;
   public static String UZ;
   public static String VA;
   public static String VB;
   public static String VC;
   public static String VD;
   public static String VE;
   public static String VF;
   public static String VG;
   public static String VH;
   public static String VI;
   public static String VJ;
   public static String VK;
   public static String VL;
   public static String VM;
   public static String VN;
   public static String VO;
   public static String VP;
   public static String VQ;
   public static String VR;
   public static String VS;
   public static String VT;
   public static String VU;
   public static String khoPet;
   public static String VW;
   public static String[] VX;
   public static String[] VY;
   public static String[] VZ;
   public static String[] WA;
   public static String[] WB;
   public static String[] mTypeSkill;
   public static String[] WD;
   public static String[] mTacdung;
   public static String[] mEffSpec;
   public static String[] WG;
   public static String[] WH;
   public static String[] WI;
   public static String[] WJ;
   public static String[] WK;
   public static String[] mHelpAutoMPHP;
   public static String[] mAutoFire;
   public static String[] mHelpAutoFire;
   public static String[] mStringDownload;
   public static String[] WP;
   public static String[] WQ = null;
   public static String[] WR = null;
   public static String[] WS = null;
   public static String[] WT = null;
   public static String[] WU = null;
   public static String[] WV = null;
   public static String[] WW = null;
   public static String[] WX = null;
   public static String[] WY = null;
   public static String[] WZ = null;
   public static String[] XA;
   public static String[] XB;
   public static String[][] XC;
   public static String autoRepeatQuest;
   public static String XE;
   public static String XF;
   public static String XG;
   public static String XH;
   public static String XI;
   public static String XJ;
   public static String XK;
   public static String XL;
   public static String XM;
   public static String XN;
   public static String XO;
   public static String XP;
   public static String XQ;
   public static String XR;
   public static String autoSuperBoss;
   public static String XT;
   public static String XU;
   public static String XV;
   public static String XW;
   public static String XX;
   public static String XY;
   public static String cmdQuickOpen;
   public static String fullItemQuickOpen;
   public static String YB;
   public static String chooseSpeedUpMenu;
   public static String chooseSpeedupTitle;
   public static String percent;
   public static String successSpeedUp;
   public static String YG;
   public static String YH;
   public static String YI;
   public static String YJ;
   public static String YK;
   public static String YL;
   public static String YM;
   public static String YN;
   public static String YO;
   public static String YP;
   public static String YQ;
   public static String YR;
   public static String notEnoughXuHanhTrinh;
   public static String titleAutoPB;
   public static String notifyOnAutoPB;
   public static String notifyOffAutoPB;
   public static String noAutoPB;

   public static void loadT() {
      VW = "Pet";
      khoPet = "Bộ Sưu Tập Thú Cưng";
      VU = "Rời Sư đồ";
      VT = "rời Sư đồ";
      VS = "Điểm sư đồ";
      VR = " muốn bái bạn làm sư phụ.";
      VQ = "Bái sư";
      VP = "Người Chơi";
      VK = "Chức danh: ";
      VL = "Sư phụ";
      VM = "Đệ tử";
      VN = "Cấp độ sư đồ: ";
      VO = "Điểm sư đồ cá nhân: ";
      VJ = "Tích Luỹ Cộng Dồn";
      VI = "Nâng Cấp Thời Trang";
      VH = "HUY HIỆU HÀNH TRÌNH";
      VG = "điểm";
      VF = "Tích tiêu Ruby";
      VE = "Cống hiến";
      VD = "Vớt bánh";
      VC = "Lịch Sử Đặt Cược";
      UU = "Đặt cược";
      UV = "Tất tay";
      UW = "Tài";
      UX = "Xỉu";
      UY = "Đã cược:";
      UZ = "Cửa:";
      VA = "Nhập số tiền (1000 - 500.000)";
      VB = "Vui lòng nhập số tiền chia hết cho 1000 và nhỏ hơn 500.000. Ví dụ 1000, 5000, 25000, ...";
      UP = "Chưa mở";
      UH = "Tên vật phẩm";
      UI = "Đấu giá";
      UJ = "Giá chót";
      UK = "Thời gian còn";
      UL = "Tên VP";
      UM = "Đ.Giá";
      UN = "G.Chót";
      UO = "T.Gian";
      UT = "Kho Huy Hiệu";
      UQ = "gây ra bộc phá tăng sức mạnh trái ác quỷ lên";
      showSkillPlayer = "chiêu thức người chơi";
      showNhanVat = "nhân vật";
      UE = "Thành Tích Nạp Thẻ";
      UG = "Tích luỹ nạp";
      UF = "Phần Thưởng Nạp";
      TV = "Bởi";
      TW = "Danh Sách Lệnh Truy Nã";
      TX = "Lệnh Truy Nã Đã Phát";
      TY = "Bạn đang ở trang đầu tiên";
      TZ = "Bạn đang ở trang cuối cùng";
      UA = "Đã Phát";
      UB = "Đã Nhận";
      UC = "Nhận thưởng";
      UD = "Danh sách trống";
      AA = "Tài khoản";
      AB = "Mật khẩu";
      del = "Xóa";
      AD = "Chat";
      close = "Đóng";
      AF = "Đăng nhập";
      AG = "Trở về";
      AH = "Thử lại";
      AI = "Thoát";
      AJ = "Mất kết nối với máy chủ. Vui lòng thử lại.";
      AK = "Tiếp";
      gohome = "Lv";
      revice = "Hồi sinh";
      AN = "Về làng";
      hoiRevice = "Bạn muốn hồi phục bằng cách?";
      hoiGoHome = "Bạn muốn về làng để hồi phục?";
      AQ = "Nhận\nKinh nghiệm";
      AR = "Tạo";
      AS = "Chọn";
      AT = "Tải";
      AU = "Menu";
      tabInven = "Hành Trang";
      AW = "Sử dụng";
      AX = "Đeo cờ chiến";
      AY = "Đồ sát";
      AZ = "Thông tin";
      BA = "Tháo cờ";
      BB = "Tắt đồ sát";
      BC = "Phím tắt";
      BD = "Phím ";
      BE = "Cộng điểm";
      tabInfo = "Thông Tin";
      BG = "Giá:";
      BH = "Nhập số điểm muốn cộng.";
      BI = "Cộng Điểm";
      BJ = "Điểm tiềm năng";
      tabSkill = "Kỹ Năng";
      BL = "Bạn muốn cộng 1 điểm vào đây.";
      BM = "Chiêu thức đã đạt cấp tối đa.";
      BN = "Mua";
      BO = "Bạn muốn mua với số lượng bao nhiêu?";
      BP = "Vui lòng chờ.";
      BQ = "Bán";
      remove = "Vứt bỏ";
      HoiSellENG = "Bạn muốn bán   %s Giá:\n %s %s?";
      HoiRemoveENG = "Bạn muốn vứt bỏ %s %s?";
      BU = "Nhiệm vụ";
      BV = " (chính)";
      BW = " (phụ)";
      tabEquip = "Trang Bị";
      BY = "Nhận";
      BZ = "Trả";
      CA = "Giao tiếp";
      CB = "Thu thập";
      CC = "Hạ gục";
      CD = "Hủy";
      CE = "Hiển thị";
      CF = "Thông tin nhóm";
      CG = "Vật phẩm nhiệm vụ";
      CH = "Nhóm";
      CI = " mời bạn vào nhóm?";
      CJ = "Chấp nhận";
      CK = "Mời vào nhóm";
      CL = "Rời";
      CM = "Kick khỏi nhóm";
      CN = "Kết bạn";
      CO = "Chức Năng";
      CP = "Trò chuyện";
      CQ = "Bang hội";
      CS = "Bang chủ";
      CR = "Tin đến";
      CT = "Thông báo";
      CU = "mục này";
      CV = "Thay đổi";
      CW = "Không có trang bị tương tự trong hành trang.";
      CX = "Đăng ký";
      checkRegister1 = "Tên và mật khẩu không được để trống.";
      CZ = "Tên nhân vật không thể để trống.";
      DA = "Xong";
      setting = "Cài đặt";
      DC = "Ưu tiên";
      DD = "Sát thương";
      DE = "Hao tổn MP";
      DF = "Số mục tiêu";
      DG = "Phạm vi lan";
      DH = "Hồi chiêu";
      typeSkill = "Chiêu thức";
      autoMPHP = "tự hồi phục";
      autoFire = "Tự động đánh";
      on = "Bật ";
      off = "Tắt ";
      DN = "muốn thêm bạn vào danh sách bạn bè.";
      DO = "Không có ai trong danh sách.";
      DP = "Danh sách bạn bè";
      DQ = "Danh sách đen";
      DR = "Cập nhật";
      DS = "Trang sau";
      DT = "Trang trước";
      DU = "Xóa bạn";
      DV = "Sự kiện";
      DW = "Lời mời kết bạn";
      DX = "Mời vào nhóm";
      DY = "Xem";
      DZ = "Cảm ứng phím";
      EA = "Cảm ứng chạm";
      cmdget = "Lấy ra";
      EC = "Cất vào";
      ED = "Đang kiểm tra dữ liệu trò chơi. Vui lòng chờ.";
      manaLost = "không đủ năng lượng";
      fullInven = "Hành trang đầy";
      autoGetItem = "tự nhặt đồ";
      EH = "Mức độ hoàn thành";
      EI = "Đã hoàn thành";
      EJ = "Phần thưởng:";
      EK = "Trả nhiệm vụ: ";
      EL = "Lời mời thách đấu";
      EM = "Thách đấu";
      EN = "%s muốn mời bạn vào 1 trận đấu 1vs1. Mức cược %s.";
      tacdung = "Tác dụng";
      EP = "Học";
      EQ = "gây";
      ER = "trong";
      ES = "Không thể kết nối với máy chủ. Vui lòng kiểm tra lại mạng di động và kết nối lại.";
      ET = "Lấy dữ liệu thất bại vui lòng thử lại.";
      EU = "Khu";
      bery = "Beri";
      EW = "Ruby";
      QF = "Extol";
      EX = "Email hoặc số điện thoại";
      EY = "Mật khẩu";
      EZ = "Tên nhân vật";
      nhanduoc = "Nhận được:";
      FB = " (lặp)";
      FC = "Nhiệm vụ mới";
      FD = "Hãy đến gặp %s để nhận nhiệm vụ mới.";
      FE = "Thông tin nhiệm vụ";
      FF = "Dịch chuyển";
      FG = "Bạn muốn bán ";
      FH = "Trắng";
      FI = "Bạn không có vật phẩm màu trắng nào trong hành trang.";
      FJ = "Trắng-Xanh";
      FK = "Bạn không có vật phẩm màu trắng và xanh lá nào trong hành trang.";
      FL = "Bán nhiều";
      FM = "vật phẩm";
      FN = "Bạn muốn thoát game? Nhân vật của bạn sẽ vẫn tiếp tục luyện tập.";
      FO = "Bạn muốn thoát khỏi trò chơi?";
      FP = "Bạn có muốn chuyển sang chế độ xóa nhân vật?";
      FQ = "ngày";
      FR = "giờ";
      FS = "phút";
      FT = "nhân vật sẽ bị xóa vĩnh viễn sau";
      FU = "nhân vật đang bị khóa, được mở sau";
      FV = "Xóa nhân vật";
      FW = "Đang nạp ";
      FX = "Đang nạp dữ liệu.";
      FY = "Đăng xuất";
      FZ = "tôi là người hỗ trợ";
      GA = "Vị trí ";
      GB = "Tự do";
      GC = "Màn hình";
      GD = "Vào game";
      GE = "Chọn hỗ trợ";
      tabAttribute = "Tiềm Năng";
      GG = "Bạn không còn điểm tiềm năng?";
      GH = "Đang đăng nhập. Vui lòng chờ.";
      GI = "Kênh thế giới";
      GJ = "Nhập nội dung";
      GK = "Nâng cấp";
      GL = "nguyên liệu";
      GM = "Lấy ra";
      GN = "Bỏ vào";
      GO = "Cường Hóa";
      GP = "Tách vật phẩm";
      split = "Phá hủy";
      joinItem = "Ghép Nguyên Liệu";
      join = "Ghép";
      nhapsoluongmuonghep = "Nhập số lượng bạn muốn ghép.";
      chuyenkeypad = "Chuyển sang dùng phím ảo";
      chuyentouch = "Chuyển sang dùng chạm";
      tatdosat = "Tắt trạng thái đồ sát";
      batdosat = "Trạng thái Đồ Sát đã bật";
      trade = "Giao Dịch";
      strlock = "Khóa";
      tradeMoney = "Nhập Tiền";
      strconfirm = "Xác Nhận";
      nhapsotien = "Nhập số tiền bạn muốn chuyển";
      eventTrade = "Lời mời giao dịch";
      yeucaugiaodich = "muốn mời bạn thực hiện một giao dịch.";
      nhapsoluongmuongiaodich = "Nhập số lượng bạn muốn giao dịch.";
      playerShiper = "tôi là người chuyển hàng";
      ship = "Vận Chuyển";
      changeship = "Đổi Hàng";
      HJ = "Thông tin bản thân";
      HK = "Xp: ";
      HL = "Hãy chọn cho tôi một người bạn nào";
      HM = "Tôi sẽ hỗ trợ cho bạn,lên đường thôi";
      allMaterial = "Tất cả";
      HO = "Rương đồ";
      HP = "Tự động cất";
      HQ = "Bạn muốn tất cả nguyên liệu và đá khảm tự động được bỏ vào rương mỗi khi về làng?";
      HR = "Không thể thay đổi trạng thái khi đang bị trọng thương";
      soluong = "Số lượng";
      HT = "Kỹ năng này chỉ được sử dụng khi đánh trên biển";
      HU = "Bạn đang đầy máu";
      HV = "Bạn đang đầy năng lượng";
      HW = "cấu hình thấp";
      HX = "Thực hiện đúng dãy kỹ năng để đánh thức nhân vật";
      skillActive = "Chiêu Chủ Động";
      skillActiveSea = "Chiêu Trên Biển";
      skillJob = "Chiêu Nghề Nghiệp";
      skillBuff = "Chiêu Hỗ Trợ";
      skillPassive = "Chiêu Nội Tại";
      ID = "Chiêu Ác Quỷ";
      IE = "Chiêu Haki";
      IF = "Chiêu ác quỷ chủ động";
      IG = "Chiêu ác quỷ nội tại";
      IH = "Chiêu ác quỷ hổ trợ";
      II = "Chiêu haki chủ động";
      IJ = "Chiêu haki nội tại";
      IK = "Chiêu haki hổ trợ";
      newGame = "Chơi mới";
      changeAcc = "Đăng nhập\ntài khoản";
      IN = "Bạn đã đang ký thành công tài khoản.";
      IO = "Hướng Dẫn";
      IS = "Bỏ Qua";
      IT = "Hải tặc";
      IU = "Chúc bạn chơi game vui vẻ";
      IV = "Đã sở hữu";
      IW = "Hủy Nv";
      daTrangBi = "Đã trang bị";
      IY = "món";
      IZ = "Bạn muốn cộng bao nhiêu điểm tiềm năng vào ";
      morong = "Mở rộng";
      laytatca = "Lấy hết nguyên liệu";
      muonlayrabaonhieu = "Bạn muốn lấy ra bao nhiêu ";
      nhapsoluong = "Nhập số lượng.";
      KH = "Bạn muốn cất vào bao nhieu ";
      KI = "Tìm kiếm";
      KJ = "Sẵn sàng";
      KK = "Hủy tìm";
      KL = "Chào mừng bạn tham gia vào đấu trường PvP.";
      KM = "Đang tìm kiếm đối thủ";
      KN = "Bạn có 30s để sẵn sàng.\nThời gian còn lại là: ";
      KO = "Bạn vừa hủy quá trình tìm kiếm đối thủ.";
      KP = "Điểm PvP: ";
      KQ = "Thắng/thua: ";
      KR = "Hãy chờ đối thủ sẵn sàng.";
      KS = "Đối thủ đã sẵn sàng.\nThời gian còn lại là:";
      KT = "Đang vào trận đấu.";
      KU = "Bạn chưa bỏ vật phẩm muốn nâng cấp vào.";
      KV = "Bạn muốn mua ";
      KW = "Đánh: ";
      KX = "Hỗ trợ: ";
      KY = "Chưa học chiêu hỗ trợ";
      KZ = "Điểm nội tại nhóm";
      LA = " Lên cấp";
      LB = "Hỗ trợ";
      LC = "Trang chủ";
      LD = "Diễn đàn";
      LE = "Đổi mật khẩu";
      LF = "Quên mật khẩu";
      LG = " muốn vào party của bạn.";
      LH = "Vào nhóm";
      tabTestAdmin = "Admin Test";
      LJ = "Khảm";
      LK = "Đục lỗ";
      LL = "Bạn chưa bỏ vật phẩm vào.";
      LM = "Bạn chưa bỏ đá muốn khảm vào.";
      LN = "Khảm vật phẩm";
      LO = "Đục lỗ vật phẩm";
      LP = "Tách đá";
      LQ = "Lấy đá khảm";
      LR = "Ghép đá khảm";
      LS = "Mở tiếp";
      LT = "Ghép đá";
      loadGame = "Chơi tiếp";
      LV = "Nạp Thẻ";
      LW = "Đang gởi thông tin nạp thẻ.Vui lòng chờ.";
      LX = "Bạn muốn thoát game và trở về màn hình đăng nhập?";
      LY = "Đã khóa";
      LZ = "Bạn chưa nhập số lượng muốn ghép.";
      MA = "Ghép tiếp";
      MB = "Âm thanh";
      MC = "Nhạc nền";
      MD = "Hiệu ứng";
      ME = "Tháo ra";
      MF = "Danh Sách";
      MG = "Tự dùng hồi sinh";
      MH = "Tự động hồi sinh đang bật";
      helpAutoRevice = "Sử dụng vật phẩm hồi sinh khi chết.";
      MJ = "Vượt RedLine thất bại";
      MK = "Đã vượt qua được RedLine";
      IP = "Bắt đầu";
      IQ = "Chọn cờ";
      IR = "Xóa bộ nhớ";
      ML = "Bộ nhớ tạm sẽ được xóa. Vui lòng khởi động lại game.";
      MM = "Không thể kết nối. Chạm lên màn hình để thử lại.";
      Clan = "Băng";
      anhem = "Anh em";
      phuttruoc = " phút trước";
      gio = " giờ";
      thuyentruong = "Thuyền trưởng";
      thuyenpho = "Thuyền phó";
      hoatieu = "Hoa tiêu";
      thanhvien = "Thuyền viên";
      tangqua = "Tặng quà";
      nhiemvu = "Nhiệm vụ";
      capdo = "Cấp độ";
      kickClan = "Trục xuất";
      strDonate = "Tặng quà";
      phongchuc = "Phong chức";
      banmuon = "Bạn muốn ";
      ND = "rời khỏi băng?";
      clanLeave = "Rời băng";
      chiso = "Chỉ Số";
      NF = "Nhập vào câu thông báo băng mới.";
      NG = "Thông Báo Bang";
      NH = "Từ chối";
      NI = " muốn xin gia nhập Băng hải tặc của bạn?";
      NJ = "Đóng góp";
      NK = "Bạn muốn chọn ";
      NL = " làm cờ hiệu cho Băng của mình?";
      NM = "Mời vào Băng";
      NN = "Xin vào Băng";
      NO = "Lời mời vào Băng";
      NP = " muốn mời bạn vào Băng.";
      NQ = "Chuyển hóa";
      NR = "Chuyển Cường Hóa";
      NS = "Tỉ lệ: ";
      NT = "Bạn muốn thực hiện chuyển số cường hóa 2 món đồ với mức phí là ";
      NU = "Bạn cần cài đặt tự động đánh trước";
      NV = " (băng)";
      NW = "Nâng cấp";
      NX = "ngày trước";
      NY = "1 tuần trước";
      NZ = "Bạn";
      PA = "Kho băng";
      PB = "Trùng sinh";
      PC = "Trùng sinh: ";
      PD = "Thông báo";
      PE = "Ha ha";
      PF = "Dưới 18 tuổi chỉ có thể chơi 180 phút 1 ngày.";
      PG = "Nhận quà";
      PH = "Đã nhận";
      PI = "Thành tích cuối";
      PJ = "Chưa bán";
      PK = "hiển thị tên";
      PQ = "Chưa có dữ liệu";
      PL = "Trang ";
      PM = " người ở phòng chờ.";
      showHat = "hiển thị nón";
      PO = "vũ khí thời trang";
      PP = "Trang";
      PR = "Nhận về";
      PS = "Dừng bán";
      PT = "Vũ khí - Nón";
      PU = "Trang phục";
      PV = "Trang sức";
      PY = "Cường hóa Ác quỷ";
      PZ = "Cường Hóa Kỹ Năng";
      QA = "Cửa hàng";
      QB = "hiện tại";
      QC = "Phó Bảng";
      max = "Max";
      QE = "Cấp độ tối đa";
      lvDevil = "Cấp ác quỷ: ";
      QH = "Trang trí";
      QI = "Đổi quà";
      QJ = "Kiểm tra";
      QK = "Quà tặng";
      QL = "Chơi quá 180 phút mỗi ngày sẽ hại cho sức khỏe.";
      QM = "Đã vượt qua thác lên trời";
      QN = "Vượt thác thất bại";
      QQ = "Nhấn tìm kiếm khi đã sẵn sàng";
      QO = "Đang tìm kiếm đối thủ cho bạn";
      QP = "Đang vào trận đấu";
      open = "Mở";
      tabQuest = "Nhiệm Vụ";
      QT = "WANTED";
      QU = "Không có quái vật sự kiện nào ở gần bạn và chỉ nó thể ném cầu khi gán vào thanh kỹ năng.";
      QV = "1 Cấp độ của cậu hiện tại không đủ. Hãy quay lại đây khi đạt cấp độ ";
      QW = "cảnh nền";
      RG = "Chat nhanh";
      server = "Sv";
      QY = "Đổi đồ";
      QZ = "Bạn chưa xét bộ trang bị nào cho chức năng này cả.";
      RA = " thay đổi hoàn tất.";
      RB = " thiết lập hoàn tất.";
      RC = "Xét nhanh";
      RD = "Nguyên liệu";
      RE = "Đá khảm";
      RF = "Cả hai";
      KC = "Lấy hết đá khảm";
      KD = "Cất hết nguyên liệu";
      KE = "Cất hết đá khảm";
      RH = "Hệ thống";
      RI = "Bạn đã mất kết nối với máy chủ và hệ thống đã tự đăng nhập lại lúc: ";
      RJ = "Hoạt động: ";
      RK = "Thông Thạo";
      RL = "Fanpage";
      RM = "Hoàn mỹ";
      RN = "Hoàn Mỹ";
      RO = "Bạn chưa bỏ hải thạch vào.";
      RP = "Chế tác: ";
      RQ = "Kích";
      RR = "Kích Dòng Ẩn";
      RS = "Kho Báu";
      RT = "Gruuừ..ừ ..ừ ...";
      RU = "Gâu gâu gâu";
      RV = "Đập";
      RW = "Cộng Chế Tác";
      RX = "Trừ chế tác: ";
      RY = "Giao hữu";
      RZ = "Siêu hạng";
      SA = "%s thách đấu bạn vào 1 trận đấu 1vs1. Phí %s ruby cho thông báo người thua chịu.";
      SB = "Đá Siêu Cấp";
      SC = "Đá siêu cấp";
      SD = "Đá nguyên liệu";
      SE = "Thách đấu";
      SF = "Thách đấu Băng";
      SG = "Danh sách đấu";
      SH = "Sắp xếp";
      SI = "Vị trí ";
      SJ = "Cần có đủ đá muốn đập siêu cấp và đá nguyên liệu để thực hiện thao tác này.";
      SK = " muốn thách đấu với băng của bạn. Phí 10 ruby để thông báo đội thua trả.";
      SL = "Ghép đồ";
      SM = "Ghép trang bị";
      showSkillBuff = "hiển thị bổ trợ";
      SO = "tai thỏ";
      SP = "Chức năng đang xây dựng";
      SQ = "Rớt cấp: ";
      SR = "Siêu Cường Hóa";
      SS = "Cường Hóa DIAL";
      ST = "Cường hóa +";
      SU = "Vui lòng lựa chọn cấu hình phù hợp?";
      SV = "(Đề xuất Rất thấp cho Iphone 4 về trước. Thấp cho Iphone 6 về trước.)";
      SW = "Thấp";
      SX = "Rất thấp";
      SY = "Cao";
      thongtinchiso = "--- Chỉ số ";
      SZ = "--- Thông tin ---";
      TC = "--- Đá Khảm ---";
      thongtinfullset = "--- Đủ bộ ---";
      PW = "Nguyên Liệu";
      PX = "Vật Phẩm";
      TD = "Bán Bery";
      TE = "Bạn muốn bán bao nhiêu triệu beri?";
      TF = "Cộng ";
      TG = "Chức năng mới giúp bạn so sánh chỉ số món đồ này với trang bị đang mặc nếu cùng cấp cường hóa.";
      TH = "Xóa ghi nhớ";
      TI = "Với nguyên liệu và vật phẩm hãy nhận về túi đồ rồi bán lên từ đó.";
      TJ = "Đánh giá";
      TK = "Chặn lời mời";
      TL = "Bạn đang bật chặn tin nhắn từ người lạ.";
      TM = "Máy chủ đang bảo trì định kỳ từ 5h đến 6h mỗi ngày. Vui lòng đăng nhập lại sau.";
      TN = "Bạn muốn chọn lấy %s từ %s?";
      TO = "Bạn chưa chọn món nào cả từ hộp quà.";
      TP = " Bậc ";
      tabSieuBoss = "Siêu trùm";
      TR = "Tặng Ruby";
      TS = "Rương quà";
      TT = "Mổ";
      chuan = " Chuẩn";
      VX = new String[]{"Đồ sát", "Sát nhân", "Đấu trường", "Chiến đấu", "Đỏ", "Lục", "Lam", "Vàng", "Tím", "Cam", "Hồng"};
      VY = new String[]{"Q", "W", "E", "R", "T", "Y"};
      VZ = new String[]{"Sức Mạnh", "Phòng thủ", "Thể Lực", "Tinh Thần", "Nhanh Nhẹn"};
      WA = new String[]{"Tất cả", "Võ sĩ", "Kiếm khách", "Đầu bếp", "Hoa tiêu", "Xạ thủ"};
      String[][] var10000 = new String[][]{new String[0], {"Luffy 1", "Luffy 2"}, {"Zoro 1", "Zoro 2"}, {"Sanji 1", "Sanji 2"}, {"Nami 1", "Nami 2"}, {"Ussop 1", "Usoop 2"}};
      String[] var0 = new String[]{"Kiểu 1", "Kiểu 2"};
      WB = new String[]{"Att", "Magic", "Def", "Cri", "Cri.D", "Eva"};
      mTypeSkill = new String[]{"Không xác định", "Tấn công", "Hỗ trợ", "Nội tại", "Tấn công trên biển", "Lỗi type=4"};
      mTacdung = new String[]{"tất cả", "Bản thân", "mình + bạn", "đối thủ"};
      WD = new String[]{"Vật phẩm", "Dược Phẩm", "Vàng"};
      mEffSpec = new String[]{"Không có gì", "Choáng", "Chảy máu", "Giảm công", "Giảm thủ", "Hoa mắt", "Điện giật", "Lửa cháy", "Trói chân", "Hút năng lượng", "Trúng độc"};
      WG = new String[]{"", "Võ Sĩ chỉ dành cho những người có thể lực và sức mạnh từ đôi tay là vô hạn.", "Kiếm Khách không đơn giản là người biết dùng kiếm mà còn phải hiểu về nó.", "Đầu Bếp trên thuyền hải tặc có gì đặt biệt à... cứ nhìn vũ khí của ta thì biết.", "Hoa Tiêu là công việc không chỉ biết mà còn phải điều khiển được thời tiết nữa.", "Xạ Thủ người anh hùng của biển cả chính là ta, khẩu súng này chính là niềm tự hào của ta."};
      WH = new String[]{"Nguyên liệu cường hóa", "Đá nguyên liệu thô", "Tăng 50% cường hóa thành công ", "Bảo hiểm cường hóa", "Tăng 100% cường hóa thành công"};
      WI = new String[]{"Tên băng: ", "Thuyền trưởng: ", "Cờ hiệu: ", "Cấp độ: ", "Th/viên: ", "Hạng: ", "Ruby: ", "Thông Báo"};
      WJ = new String[]{"Danh sách", "Kẻ thù", "Cài đặt", "Chọn cờ", "Đồ sát", "Cảm ứng", "Nhóm", "Chat nhanh", "Thoát", "Loa", "Bang hội", "Nạp thẻ", "Đổi đồ", "Đấu giá", "Sư đồ", "Pet"};
      var0 = new String[]{"Thuyền Trưởng", "Thuyền Phó", "Hoa Tiêu"};
      WK = new String[]{"Chào mừng đến với Hải tặc tí hon.\nMọi ý kiến đóng góp xin đăng tại diễn đàn haitactihon.com", "Nếu bạn là 1 người mới hãy chọn Hướng Dẫn để chúng tôi có thể giúp bạn, nếu không bạn có thể chọn Bỏ Qua", "Đây là phần hiển thị máu , năng lượng và cấp độ", "Các kỹ năng của bạn sẽ được hiển thị ở đây", "Bấm phím tương ứng để dùng", "Chạm vào để dùng", "Bấm các phím điều hướng hoặc 2,4,6,8 để di chuyển", "Chạm vào đây nếu bạn muốn di chuyển", "Nếu bạn muốn di chuyển đến đâu cứ chạm vào đó", "Bạn sẽ đổi mục tiêu khi bấm phím trái", "Bạn sẽ đổi mục tiêu khi chạm vào đây", "Muốn giao tiếp với ai hay đánh con quái nào bạn chỉ cần chạm vào đó", "Muốn trò chuyện với những người xung quanh thì bạn hãy nhấn dấu *", "Muốn trò chuyện với những người xung quanh thì bạn hãy chạm vào đây", "Bạn vừa có 1 tin nhắn hãy mở ra xem ai đã gởi bằng cách nhấn #", "Bạn vừa có 1 tin nhắn hãy mở ra xem ai đã gởi bằng cách chạm vào đây", "Đây là nơi hiển thị thông tin mục tiêu của bạn", "Bạn có đến 2 thanh kỹ năng hãy chuyển đổi qua lại bằng phím 0", "Bạn có đến 2 thanh kỹ năng hãy chuyển đổi qua lại bằng cách chạm vào đây", "chuyển mục tiêu vào vật phẩm để nhặt nó", "Chạm vào vật phẩm để nhặt nó", "Vật phẩm nhặt được sẽ vào hành trang.Khi cần mở hành trang bạn hãy bấm phím trái", "Vật phẩm nhặt được sẽ vào hành trang.Khi cần mở hành trang bạn hãy chạm vào đây", "Đây là hành trang của bạn. Nếu muốn dùng 1 món đồ nào đó hãy chọn nó và sử dụng.", "Các món có số lượng bạn còn có thể gán vào 1 ô kỹ năng để có thể dùng nhanh đấy.", "Tiếp theo là mục trang bị, nơi hiển thị những thứ bạn mang trên mình.", "Bạn có thể thay thế 1 món bất kỳ bằng cách chọn vào nó.", "Giờ thì hãy chạy 1 mạch vào làng để gặp trưởng làng nào.", "Những người có dấu ! nghĩa là họ có nhiệm vụ giao cho bạn hãy gặp họ để nhận.", "Mở lại hành trang để xem thông tin nhiệm vụ", "Đây là nơi hiển thị các nhiệm vụ cũng như thông tin chi tiết nhất về các nhiệm vụ đó.", "Giờ thì hãy thực hiện nhiệm vụ nào.", "Bạn vừa lên cấp và sức mạnh vừa tăng lên đáng kể rồi đấy.Vào lại hành trang xem ta đã mạnh thế nào rồi.", "Mục này chính là kỹ năng giúp bạn có thể biết mọi thứ về chiêu thức của mình.", "Đối với các chiêu thức kích hoạt bạn có thể gán chúng vào thanh kỹ năng để dùng nhanh.", "Ra ngoài thử xem kỹ năng chúng ta tới đâu rồi nào.", "Phần này dùng để hiển thị thông tin chi tiết và tiềm năng của bạn.", "Thanh bên trái chính là mọi thứ về thông tin của bạn.", "Thanh bên phải hiển thị phần tiềm năng cũng như cộng điểm mỗi khi bạn lên cấp", "Bạn đang còn khá nhiều điểm đấy hãy cộng vào thử xem", "Mục cài đặt này có rất nhiều tính năng cần thiết trong trò chơi đấy", "Chạm vào đây để hiện các chức năng khác trong trò chơi", "Chức năng Giao dịch với người chơi khác vừa được mở. Khi cần giao dịch với người khác hãy giao tiếp với họ và chọn giao dịch.", "Giờ thì bạn đã có thể thực hiện chức năng cường hóa. Hãy đến gặp NPC Johny để tăng sức mạnh cho bản thân.", "Bản đồ săn Boss đã mở. Hãy đến gặp NPC Yoshaku để thử sức nào."};
      XC = new String[][]{{"Nhặt tất cả vật phẩm", "Nhặt vật phẩm tím trở lên", "Nhặt vật phẩm cam trở lên", "Không nhặt vật phẩm"}, {"Nhặt tất cả dược phẩm", "Chỉ nhặt dược phẩm máu", "chỉ nhặt dược phẩm năng lượng", "không nhặt dược phẩm"}, {"Nhặt tất cả vàng", "Không nhặt vàng"}};
      mHelpAutoMPHP = new String[]{"Dùng khi máu dưới ", "Dùng khi năng lượng dưới ", "Ưu tiên dùng dược phẩm nhỏ", "Ưu tiên dùng dược phẩm lớn"};
      mAutoFire = new String[]{"Tất cả chiêu thức", "Chỉ chiêu cơ bản", "Không tự động"};
      mHelpAutoFire = new String[]{"Đánh tất cả chiêu thức", "Chỉ đánh chiêu ", "Không tự động đánh", "Không dùng chiêu ", "Tự động dùng chiêu "};
      mStringDownload = new String[]{"bg", "Hình nền", "big", "Nhân vật", "eff", "Hiệu ứng", "interface", "Giao diện", "map", "Địa hình", "mfont", "Font chữ", "point", "Giao diện cảm ứng", "hinhkhonglo", "Khổng lồ"};
      WP = new String[]{"Số Serial", "Mã Thẻ"};
      WQ = new String[]{"Họ và tên", "Năm sinh(ngày.tháng.năm)", "Địa chỉ thường trú", "Chứng minh nhân dân", "Ngày cấp(ngày.tháng.năm)", "Nơi cấp", "Số điện thoại/Email"};
      WR = new String[]{"Nguyễn Văn A", "01.01.1990", "Bình Chánh Tp Hồ Chí Minh", "024024024", "10.10.2010", "Tp Hồ Chí Minh", "0909123456"};
      var0 = new String[]{"email/số điện thoại", "từ 6 đến 12 ký tự"};
      WS = new String[]{"Chờ giao dịch", "Đang rao bán", "Đã bán", "Hết hạn", "Đã mua"};
      WT = new String[]{"Bộ trang bị vàng", "Bộ trang bị đỏ"};
      WU = new String[]{"Phòng thủ trụ trên", "Phòng thủ trụ giữa", "Phòng thủ trụ dưới", "Tập trung phòng thủ", "Tấn công trụ trên", "Tấn công trụ chính", "Tấn công trụ dưới", "Tổng tấn công", "Tâp trung ăn bùa"};
      WV = new String[]{"Phó bản Nami nào", "Vượt liên ải nào anh em", "Ai săn trùm không", "1 vé Mr3 nha", "Cần vào băng", "Băng tuyển thành viên", "Cho vào nhóm với", "Ai giao dịch không"};
      WW = new String[]{"22 -> 30", "20 -> 28", "18 -> 26", "16 -> 24", "14 -> 22", "1 -> 5", " "};
      WX = new String[]{"  - Giảm né đối thủ 5%", "  - Giảm p/đ đối thủ 5%", "  - Giảm c/m,x/g đối thủ 5%", "  - Nhận từ chối tử thần", "  - Tăng chỉ số trên lên 60%", "    Sát thương chuẩn 10%"};
      var0 = new String[]{"", "Sơ cấp 70%", "Trung cấp 50%", "Cao cấp 30%", ""};
      WY = new String[]{"Gợi ý tân thủ đến Thị trấn vỏ sò\n Phụ bản săn trùm\n Vận hàng\n Nhiệm vụ hằng ngày\n Khóa bảo vệ\n Chi tiết hãy đến bảng hướng dẫn(làng này hoặc các làng trước)", "Gợi ý tân thủ đến Thị trấn Orang\n Cường hóa trang bị\n Vòng quay may mắn\n Thách đấu\n Chi tiết hãy đến bảng hướng dẫn(làng này hoặc các làng trước)", "Gợi ý tân thủ đến Làng Sirup\n Cường hóa ác quỷ\n Chiếm đảo\n Chi tiết hãy đến bảng hướng dẫn(làng này hoặc các làng trước)", "Gợi ý đến Nhà hàng Barati\n Băng hải tặc\n Phụ bản băng\n Chi tiết hãy đến bảng hướng dẫn(làng này hoặc các làng trước)", "Gợi ý đến làng hạt dẻ\n Phụ bản bảo vệ kho báu Namie\n Siêu trùm\n Chi tiết hãy đến bảng hướng dẫn(làng này hoặc các làng trước)", "Gợi ý đến Thị trấn khởi đầu\n Lệnh truy nã\n Siêu trùm\n Thách đấu\n Chi tiết hãy đến bảng hướng dẫn(làng này hoặc các làng trước)"};
      WZ = new String[]{"Chặn tất cả", "Người lạ nhắn tin", "Mời kết bạn", "Mời vào nhóm", "Mời giao dịch", "Mời thách đấu", "Hiển thị lại"};
      XA = new String[]{"Chặn tất cả mọi giao tiếp kể cả bạn bè", "Chỉ có bạn bè mới có thể nhắn tin", "Bỏ qua lời mời kết bạn", "Bỏ qua lời mời vào nhóm", "Bỏ qua lời mời giao dịch", "Bỏ qua lời mời thách đấu", "Hiển thị bảng này khi chạy lại game"};
      XB = new String[]{"", " nhắn tin cho bạn ", " gởi lời mời kết bạn ", " mời bạn vào nhóm ", " muốn giao dịch với bạn ", " thách đấu với bạn ", ""};
      XG = "Bạn đã hết bánh mì. Chế độ Auto nhiệm vụ lặp đã được tắt.";
      XH = "Túi đồ của bạn cần ít nhất 2 ô trống để hoàn thành nhiệm vụ. Chế độ Auto nhiệm vụ lặp đã được tắt.";
      XI = "Map này không có nhiệm vụ lặp. Chế độ Auto nhiệm vụ lặp đã được tắt.";
      autoRepeatQuest = "Auto NV Lặp";
      XE = "Bạn có muốn kích hoạt chế độ auto nhận và trả nhiệm vụ lặp không?";
      XF = "Đồng ý";
      XJ = "Chế độ Auto nhiệm vụ lặp đã được tắt.";
      XK = "- AUTO NVL: ON";
      XL = "Bạn vừa thay đổi map. Chế độ Auto nhiệm vụ lặp đã được tắt.";
      XM = "Bạn không đủ điều kiện thể nhận nhiệm vụ lặp. Chế độ Auto nhiệm vụ lặp đã được tắt.";
      XN = "Cấp độ của bạn không thể nhận nhiệm vụ lặp. Chế độ Auto nhiệm vụ lặp đã được tắt.";
      XO = "hoàn thành";
      XP = "Không tìm thấy";
      XQ = "chỉ dành cho";
      XR = "Tìm mục tiêu";
      XT = "Bạn có muốn kích hoạt chế độ Auto đánh super boss không?";
      XU = "Chế độ Auto đánh super boss đã được tắt.";
      autoSuperBoss = "Auto Siêu Boss";
      XV = "- AUTO SUPER BOSS: ON";
      XW = "Đã tiêu diệt Super Boss. Chế độ Auto đánh Super Boss đã được tắt.";
      XX = "Không tìm thấy Super Boss. Chế độ Auto đánh Super Boss đã được tắt.";
      XY = "Bạn vừa bị Super Boss kick về làng. Chế độ Auto đánh Super Boss đã được tắt.";
      cmdQuickOpen = "Mở nhanh";
      fullItemQuickOpen = "Túi đồ của bạn phải trống ít nhất 3 ô.";
      chooseSpeedUpMenu = "Chọn Tốc Độ Game";
      chooseSpeedupTitle = "Lựa chọn tốc độ trò chơi";
      percent = "%";
      successSpeedUp = "Đã lựa chọn tốc độ ";
      YB = "SPEED_UP";
      YG = "Cấu hình đã được thiết lập. Hãy khởi động lại trò chơi";
      YI = " đã hết. Tự động nâng cấp trang phục đã dừng.";
      YJ = "thất bại";
      YH = "Nguyên liệu";
      YK = " của bạn không đủ. Tự động nâng cấp đã dừng.";
      YN = "Ngôi sao may mắn";
      YM = "Mai rùa";
      YL = "Khiên";
      YO = " và ";
      YP = "Xu hành trình";
      YQ = "Bạn chưa nhập số lượng";
      YR = "Bạn không có xu hành trình";
      notEnoughXuHanhTrinh = "Xu hành trình của bạn đã hết";
      titleAutoPB = "Auto PB Chiếm Đảo";
      notifyOnAutoPB = "Bạn đã bật Auto hỗ trợ Phó Bảng Chiếm Đảo. Chức năng sẽ hỗ trợ bạn tự động chọn mục tiêu tấn công khi tham gia chiến đấu trong phó bảng chiếm đảo.";
      notifyOffAutoPB = "Chế độ Auto PB Chiếm Đảo đã được tắt.";
      noAutoPB = "Map này không hỗ trợ Auto Phó Bảng Chiếm Đảo. Chế độ Auto hỗ trợ Phó Bảng Chiếm Đảo đã được tắt.";
   }
}
